name: Generate & Deploy Site

on:
  push:
    branches:
      - main
  schedule:
    # every day at 01:00 UTC
    - cron: '0 1 * * *'
    # every Monday at 04:00 UTC
    - cron: '0 4 * * 1'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # expose environment variables to all steps
    env:
      OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
      BASE_URL:             https://alrimco.web.app
      GA_MEASUREMENT_ID:    G-EF7SY2WX3S

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            python-frontmatter \
            markdown \
            jinja2 \
            pandas \
            python-slugify \
            python-dotenv \
            openai

      - name: Generate Posts (OpenAI)
        run: python scripts/generate_post.py

      - name: Build Site (Jinja2)
        run: python scripts/build_site.py

      - name: Generate RSS Feed
        run: python scripts/generate_rss.py

      - name: Set up Node.js for Firebase
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
