name: Generate & Deploy Site

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'  # daily at 01:00 UTC

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # ← This env: must be indented exactly 4 spaces under build-deploy
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      FIREBASE_TOKEN:    ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Optional debug step — prints first 4 chars of the key (it will be masked)
      - name: Debug OpenAI key
        run: echo "OpenAI key starts with ${OPENAI_API_KEY::4}…"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-frontmatter markdown jinja2 pandas python-slugify python-dotenv openai firebase-tools

      - name: Generate Posts
        run: python scripts/generate_post.py

      - name: Build Site
        run: python scripts/build_site.py

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        # FIREBASE_TOKEN is already set at the job level
