name: Generate & Deploy Site

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'  # daily at 01:00 UTC

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-frontmatter markdown jinja2 pandas python-slugify python-dotenv openai
      - name: Generate Posts
        run: python scripts/generate_post.py

      - name: Build Site
        run: python scripts/build_site.py

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting