name: Generate & Deploy Site

on:
  # run on every push to main
  push:
    branches: [ main ]

  # run on schedule every 15 minutes (UTC)
  schedule:
    - cron: '*/15 * * * *'

  # manual trigger
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            python-frontmatter \
            markdown \
            jinja2 \
            pandas \
            python-slugify \
            python-dotenv \
            openai \
            requests

      - name: Generate Posts (OpenAI)
        run: python scripts/generate_post.py

      - name: Build Site (Jinja2)
        run: python scripts/build_site.py

      - name: Generate RSS Feed
        run: python scripts/generate_rss.py

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting
